In [5]:
import numpy as np

In [6]:
np.power(5,2)

25

## Exercise
Initialize the following matrices

A matrix with entries of integers from 1 through 12, with the dimensions 3x4.

Define a scalar_mat() function which takes in 2 elements - 'n' which determines the nxn dimensions of the scalar matrix and 'a' the entry which fills all positions in the primary diagonal. Use this function to create a 4x4 scalar matrix with diagonal elements as 256.

A 5x5 identity matrix.

In [10]:
np.reshape(np.arange(1,13),(3,4))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [20]:
def scalar_mat(n,a):
    scalarmatrix = np.zeros((n,n))
    for i in range(0,n):
        scalarmatrix[i][i]=a
    return scalarmatrix
    
scalar_mat(4,256)    

array([[256.,   0.,   0.,   0.],
       [  0., 256.,   0.,   0.],
       [  0.,   0., 256.,   0.],
       [  0.,   0.,   0., 256.]])

In [17]:
def scalar_mat(n,a):
    scalar_matrix = np.zeros((n,n))
    for i in range(0,n):
        scalar_matrix[i][i]=a
    return scalar_matrix

In [18]:
scalar_mat(4,256)

array([[256.,   0.,   0.,   0.],
       [  0., 256.,   0.,   0.],
       [  0.,   0., 256.,   0.],
       [  0.,   0.,   0., 256.]])

In [22]:
np.eye(5,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [24]:
Addition = a+b
print(Addition)

[[2 4]
 [5 5]]


In [28]:
Substraction = a-b
print(Substraction)

[[0 0]
 [1 3]]


In [34]:
multiplication = a*b
print(multiplication)

[[1 4]
 [6 4]]


In [35]:
#transpose of a matrix

A = np.array([[8,15,30],[43,2,9],[11,25,62]])
print(A)

[[ 8 15 30]
 [43  2  9]
 [11 25 62]]


In [36]:
AT = np.transpose(A)
print(AT)

[[ 8 43 11]
 [15  2 25]
 [30  9 62]]


In [40]:
# to calculate the determinant of the above array

np.linalg.det(AT)

-7723.0000000000055

In [41]:
# inverse of a matrix
np.linalg.inv(AT)

array([[ 0.01307782,  0.33238379, -0.13634598],
       [ 0.02330701, -0.02149424,  0.00453192],
       [-0.00971125, -0.15771073,  0.08144503]])