## solving equations in python

3x-9y=-42

2x+4y=2



In [1]:
import numpy as np

In [3]:
A= np.array([[3 ,-9],[2,4]])
print(A)

[[ 3 -9]
 [ 2  4]]


In [4]:
B =np.array([-42,2])
print(B)

[-42   2]


In [5]:
z= np.linalg.solve(A,B)
print(z)

[-5.  3.]



## Solve the below equation
x-2y-Z = -6

2x+2y-z = 1

-x-y+2z = 1

In [6]:
C =np.array([[1,-2,-1],[2,2,-1],[-1,-1,2]])
print(C)

[[ 1 -2 -1]
 [ 2  2 -1]
 [-1 -1  2]]


In [15]:
d = np.array([6,1,1])
print(d)

[6 1 1]


In [11]:
z = np.linalg.solve(C,d)
print(z)

[ 3. -2.  1.]


In [12]:
import numpy as np 
from scipy.spatial import distance

from ipywidgets import interact, interactive, fixed, interact_manual
import ipywidgets as widgets
 
from plotly.offline import download_plotlyjs, init_notebook_mode, plot, iplot
from plotly import graph_objs as go
init_notebook_mode(connected=True)
import numpy as np

import random

from IPython.display import display, Math

from bokeh.io import show, output_notebook, reset_output
from bokeh.plotting import figure, show
from scipy.stats import norm 
from bokeh import plotting as pl
from bokeh.models import HoverTool, Arrow, OpenHead, NormalHead, VeeHead, Span, ColumnDataSource, PointDrawTool, TableColumn,  DataTable


In [17]:
# Dot product

dot_product = np.dot([1,2],[3,4])
print("dot product value for is {} " .format(dot_product))

reverse_dot_product = np.dot([3,4], [1,2])
print("We swap the vectors fromt their positions, then the dot product is {}" .format(reverse_dot_product))

dot product value for is 11 
We swap the vectors fromt their positions, then the dot product is 11


In [19]:
# vector 
tools_to_show= 'box_zoom,pan,save,hover,reset,tap,wheel_zoom'        


# go by vector orientation 

def vec_plot(vec_1_ort,vec_2_ort):
    vec_1 = [0,6]
    vec_2 =[8,0]

    vec_2_ort = - vec_2_ort
    vec_1_x = vec_1[0]*np.cos(vec_1_ort)  + vec_1[1]*np.sin(vec_1_ort) 
    vec_1_y = -vec_1[0]*np.sin(vec_1_ort) +vec_1[1]*np.cos(vec_1_ort)
    
    
    vec_2_x = vec_2[0]*np.cos(vec_2_ort)  + vec_2[1]*np.sin(vec_2_ort) 
    vec_2_y = -vec_2[0]*np.sin(vec_2_ort) +vec_2[1]*np.cos(vec_2_ort)
    
    denom = (np.linalg.norm([vec_1_x, vec_1_y]) *np.linalg.norm([vec_2_x, vec_2_y]))
    numer = np.dot([vec_1_x,vec_1_y ],[vec_2_x,vec_2_y ] )
    angle_between  = np.rad2deg( np.arccos(numer/ denom))
    dot_product_value = numer
    
    
    fig = pl.figure(x_range =[0,10],
                    y_range =[0,10], 
                    plot_height =400, 
                    plot_width= 400, 
                   tools= tools_to_show,
                   x_axis_label = "x axis",
                    y_axis_label = "y axis"
                   )
    
    
    
    fig.add_layout(Arrow(end=NormalHead(fill_color="black"),
                       x_start=0,
                       y_start=0,
                       x_end=vec_1_x,
                       y_end=vec_1_y))
    
    fig.add_layout(Arrow(end=NormalHead(fill_color="black"),
                       x_start=0,
                       y_start=0,
                       x_end=vec_2_x,
                       y_end=vec_2_y))
    

    
    fig.circle(vec_1_x,vec_1_y,size = 12, color= "red")
    fig.circle(vec_2_x,vec_2_y,size = 12, color= "green")
    
    fig.text(x=6.0, y=8.0, text=["Angle between  \n =  " + str(np.round(angle_between,2)) ])
    fig.text(x=2.0, y=8.0, text=["Dot product \n value =" + str(np.round(dot_product_value,2))])
#     fig.text(x=(8-x)/2+ x, y=-(2-y)/2+(y/2), text=["R"])
    
    hover = fig.select(dict(type=HoverTool))    
    hover.tooltips = [("xvalue", "$x"), ("yvalue", "$y")]
    show(fig)
    return 

interact(vec_plot, 
                   vec_1_ort = widgets.FloatSlider(value = 0, min= 0, max =1.57, step =0.01 ),
        
                     vec_2_ort = widgets.FloatSlider(value = 0, min= 0, max =1.57, step =0.01 ), 
        
        )

interactive(children=(FloatSlider(value=0.0, description='vec_1_ort', max=1.57, step=0.01), FloatSlider(value=…

<function __main__.vec_plot(vec_1_ort, vec_2_ort)>

In [20]:
# cross product example 

vector_1 = [2, 3, 5]
vector_2 = [5,-9, 8]

cross_product_value = np.cross(vector_1, vector_2)

print("The new vector from the cross product will be vector_3  = {}" .format(cross_product_value))


The new vector from the cross product will be vector_3  = [ 69   9 -33]
